CREATE TABLE public.tec (
    color_ataque text,
    device_name text,
    direction text,
    dst text,
    dst_alpha2 text,
    dstlat double precision,
    dstloc double precision,
    dstlong double precision,
    dstname text,
    severity text,
    src text,
    src_alpha2 text,
    srclat double precision,
    srcloc double precision,
    srclong double precision,
    srcname text,
    subtype text,
    threatid text,
    time_generated timestamp without time zone
);