version: '3'
services:
  front:
    image: fdebene/norsepi
    container_name: norsepi-front
    restart: always
    ports :
      - "80:80"
     
  backend:
    image: fdebene/middleware:beta-3-alpine
    container_name: backend
    restart: always
